travis:
  secure:
    BINSTAR_TOKEN: S+gn1tfR4bkp96U99i1Gv0zcOhMqBSVWwwTgFIG4MHWQYW9JLPRkqBiHnGHYk4LP6NJg4rTSd/Topm82AB4rlbEvMuWVy+2vdKNkNWUJcedTzV8zmgs522LyHTjT9WKPY08jHfxPYnwD0nmOKuZjMifT6fEhPP5r91BeqmW81z1y6o3re389vfOQkzu7x35W9MNvS8RdL5sXF//8m2amRSoFbpeF1tHKo/ebrsd+nkkwN5O2kie/Z7w8qmV1YJypr9QOwACsgKyLD8hMShwvvqmScvA5uxPSFmfXIrpc/PBa3MHRN7I7kcjKP/G1lQq4Sighvejak7ifkWWQzxZVhyIzPv2Y+e4iBxjFpgAGx1+0g2gPlp1dDsJOx+ZT2j9hxlBGvjduhnfY1goQ4adzKO752jdfOMlrPoH+mCFxrg+5GP1sJrnA5VLQOJ5NdK5nN/BMFcA60870LReg8rBlM0yrXi4h6im4vD+1aor/j4CJETkomVhwTl63RGGVx4O9s+VV6To1fKljL0D+6Ex0+uQlXUNFfajp0JSP6cIxI+oCw1yRi2jldmNiXZJo8botxeIgSH6Pn0WtkzhKCf4Prf//tzvtvNIxxvLDCisKOzxvbFILsuDVfjjWvjheRRZTil8nWQq2OT8JkRhhmVnGEOznwnom8g0oeImxy/rPjPY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
